exports.nannyData = [
  {
    _id: '1',
    name: 'Rebecca Boyce',
    city: 'Naples',
    street: '123 Royal Palm Way',
    state: 'FL',
    zip: '12345',
    phone: '(555) 555-5555',
    image: 'http://via.placeholder.com/350x250',
    email: 'rebecca@gmail.com',
    description: 'So royal!',
    hourlyRate: 25,
    active: true,
    createdAt: '12/12/2019',
  },
  {
    _id: '2',
    name: 'Nancy Nanny',
    city: 'Boca raton',
    street: '234 Baton Road',
    state: 'FL',
    zip: '12345',
    phone: '(123) 456-7890',
    image: 'http://via.placeholder.com/350x250',
    email: 'nancy@gmail.com',
    description: 'Very nice nanny',
    hourlyRate: 20,
    active: true,
    createdAt: '01/16/2020',
  },
  {
    _id: '3',
    name: 'Audrey Aupair',
    city: 'naples',
    street: '456 Nepoli Avenue',
    state: 'FL',
    zip: '12345',
    phone: '(333) 333-3333',
    image: 'http://via.placeholder.com/350x250',
    email: 'audrey@gmail.com',
    description: 'Very nice au pair',
    hourlyRate: 30,
    active: true,
    createdAt: '02/12/2020',
  },
  {
    _id: '4',
    name: 'Betsy Babysitter',
    city: 'boca raton',
    street: '789 Beach Drive',
    state: 'FL',
    zip: '12345',
    phone: '(444) 444-4444',
    image: 'http://via.placeholder.com/350x250',
    email: 'betsy@gmail.com',
    description: 'Very nice babysitter.',
    hourlyRate: 15,
    active: true,
    createdAt: '03/20/2020',
  },
]
